[codestyle]
indent_type = 'space'
indent_width = 4
workspace_dir = '/mnt/y/2019/pg/ABC/'
lang = 'cpp'
template_file='/mnt/y/2019/pg/my_template.cpp'
[etc]
download_without_login=false
parallel_download=false
save_no_session_cache=false
